Controllers/eReaderController.cs
using BookStore.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Speech.Synthesis;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using System.Net;
using System.Data;
using System.Data.Entity;
using System.Net.Http;

namespace BookStore.Controllers
{
    public class eReaderController : Controller
    {
        private ApplicationDbContext applicationDbContext = new ApplicationDbContext();
        public ActionResult Index()
        {
            var books = applicationDbContext.eBooks.ToList();
            return View(books);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(eBook book, HttpPostedFileBase file, HttpPostedFileBase fileImage)
        { 
            if (book != null)
            {
                // Verify that the user selected a file
                if (file != null && file.ContentLength > 0)
                {
                    // extract only the filename
                    //var fileName = Path.GetFileName(file.FileName);
                    // store the file inside ~/App_Data/uploads folder
                    //var path = Path.Combine(Server.MapPath("~/eBooks"), fileName);
                    //file.SaveAs(path);
                    //BinaryReader rdr = new BinaryReader(file.InputStream);
                    //var fileByte = rdr.ReadBytes((int)file.ContentLength);

                    StreamReader rdr = new StreamReader(file.InputStream);
                    var imageByte = rdr.ReadToEnd();

                    book.FileContents = imageByte;
                    book.mimetype = Path.GetExtension(file.FileName);
                    book.BookName = file.FileName.Substring(0, file.FileName.IndexOf('.'));
                    //book.FilePath = Path.Combine(Server.MapPath("~/eBooks"), fileName);
                    book.FileName = file.FileName.Substring(0, file.FileName.IndexOf('.'));

                }
                if (fileImage != null && file.ContentLength > 0)
                {
                    BinaryReader rdr = new BinaryReader(fileImage.InputStream);
                    var imageByte = rdr.ReadBytes((int)fileImage.ContentLength);
                    book.BookImageContent = imageByte;
                    book.BookImageName = fileImage.FileName.Substring(0, fileImage.FileName.IndexOf('.'));
                    book.BookImageExtension = Path.GetExtension(fileImage.FileName);
                }

                Products products = new Products();
                products.ProductName = book.BookName;
                products.ProductDescription = book.BookDescription;
                products.ProductPrice = book.BookPrice; 
                products.ProductImage = book.BookImageContent;
                products.ProductStock = 100;
                products.ProductCatergoryId = 11;



                book.LastReadPosition = 0;
                applicationDbContext.eBooks.Add(book);
                applicationDbContext.Products.Add(products);
                applicationDbContext.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public string ReadTextFile(int id, bool? lastRead)
        {
            var book = applicationDbContext.eBooks.FirstOrDefault(x => x.Id == id);
            //string content = string.Empty;
            //var filepath = HttpContext.Server.MapPath($"~{book.FilePath}");
            //using (var stream = new StreamReader(filepath))
            //{
            string content = book.FileContents;
            //}
            //if (lastRead == true && content.Length > book?.LastReadPosition)
            //{
            //    return (content.Substring(book.LastReadPosition), book.BookName);
            //}
            //else
            //{
                return content;
            //}
        }

        //public ActionResult Test()
        //{
        //    return ReadText(1, false);
        //}

        public async Task<ActionResult> ReadText(int id, bool? lastRead)
        {
            var book = ReadTextFile(id, lastRead);
            Task<FileContentResult> task = Task.Run(() =>
            {
                using (var synth = new SpeechSynthesizer())
                {
                    using (var stream = new MemoryStream())
                    {
                        synth.SetOutputToWaveStream(stream);
                        synth.Speak(book);
                        byte[] bytes = stream.GetBuffer();
                        return File(bytes, "audio/wav"/*, book.Item2*/);
                    }
                }
            });
            return await task;
        }

        public ActionResult PlayeBook(int id, bool? lastRead)
        {
            eBook getDetails = applicationDbContext.eBooks.FirstOrDefault(x => x.Id == id);
            //dynamic result = await ReadText(id, lastRead);

            //getDetails.Content = result;
            //ViewBag.Data = "data:audio/wav;base64," + Convert.ToBase64String(result.FileContents);

            return View(getDetails);
        }

       

    }
}

Views/eReader/Create.cshtml
@model BookStore.Models.eBook

@{
    ViewBag.Title = "Create eBook";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

@using (Html.BeginForm("Create", "eReader", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal col-lg-6 offset-3">

    <h2>Create eBook</h2>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.BookName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BookName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BookName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BookDescription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BookDescription, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BookDescription, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BookGenre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BookGenre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BookGenre, "", new { @class = "text-danger" })
        </div>
    </div>

    @* <div class="form-group">
            @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FilePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FilePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FilePath, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.BookImageURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookImageURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookImageURL, "", new { @class = "text-danger" })
            </div>
        </div>*@
    <div class="form-group">
        @Html.LabelFor(model => model.BookImageName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="fileImage" id="BookImageContent" accept=".png,.jpg,.jpeg,.gif" />

            @*@Html.EditorFor(model => model.BookImageURL, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.BookImageContent, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="file" id="FileContent" accept=".txt" />

            @*@Html.EditorFor(model => model.BookImageURL, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.FileContent, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn-sm btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/eReader/Index.cshtml
@model IEnumerable<BookStore.Models.eBook>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BookImageName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BookName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BookDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BookGenre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FileName)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.FilePath)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.LastReadPosition)
        </th>
        <th>
            Action
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @{
                if (item.BookImageContent != null)
                {
                    var base64 = Convert.ToBase64String(item.BookImageContent);
                    var imgSrc = String.Format("data:image/png;base64,{0}", base64);
                    <img src="@imgSrc" width="200" height="200" />
                }
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BookName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BookDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BookGenre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FileName)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.FilePath)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.LastReadPosition)
        </td>
      
        <td>
            @Html.ActionLink("Read Book", "PlayeBook", new { id = item.Id, lastRead = false }, new { @class = "btn-sm btn-primary" })
        </td>
    </tr>
}

</table>

Views/eReader/PlayeBook.cshtml
@model BookStore.Models.eBook
@{
    ViewBag.Title = "Play eBook";
    Layout = "~/Views/Shared/_Layout1.cshtml";

}
<link href="~/Styles/StyleSheet6.css" rel="stylesheet" />
<style>
    body {
        background-color: #000000;
    }
</style>
<body>

    <div align="center">
        <h1 style="color: #838996">Media PLayer</h1>
    </div>
    <hr />

    <div align="center">
        @{
            if (Model.BookImageContent != null)
            {
                var base64 = Convert.ToBase64String(Model.BookImageContent);
                var imgSrc = String.Format("data:image/png;base64,{0}", base64);
                <img src="@imgSrc" width="600" height="400" />
            }
        }
    </div>


    <br />


    <div align="center" class="glowing">
        <span> <audio id="audioPlayer" controls src="@Url.Action("ReadText", new { id = Model.Id, lastRead = false })" /> </span>
    </div>
    <br />
    <br />
    <br />

    <div style="color: #838996; font-size: 20px" align="center">
        @Html.DisplayFor(model => model.BookName)
    </div>

    <br />


    <div style="color: #838996; font-size: 20px" align="center">
        @Html.DisplayFor(model => model.BookDescription)
    </div>

    @*@Html.Partial("_ReaderAudio", new { @id = Model.Id, @lastRead = false })*@

    <br />

    <div>
        @Html.ActionLink("Back", "Index", null, new { @class = "btn-sm btn-primary" })
    </div>


    <script>
    //$(function () {
    //    $('#audioPlayer').bind('canplay', function () {
    //        $('#audioPlayer').currentTime = 10;
    //    });
    //});

    @*var tt = '@Model.LastReadPosition';
    var audio = document.getElementById('audioPlayer');
    audio.onprogress = function () {
        if (audio.currentTime == 0) {
            audio.currentTime = 10;
        }
    }*@

    //var currentPosition = parseInt(tt);
    //element.currentTime = currentPosition;
    </script>
</body>