Controllers/SavedProductsController.cs
using BookStore.Models;
using System;
using System.Data.Entity;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web.Mvc;
using BookStore.Helpers;
using System.Configuration;

namespace BookStore.Controllers
{
    public class SavedProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: SavedProducts
        public ActionResult Index()
        {

            var wishListsProducts = db.WishListsProducts.Include(w => w.Products).Include(w => w.WishLists);
            return View(wishListsProducts.ToList());
        }

        public ActionResult DisplayWishlist(WishLists wishLists, WishListsProducts wishListsProducts, int? Id, string Wishlisturl)
        {
           var Idc = wishListsProducts.ListId;
            var wlistprod = db.WishListsProducts.Include(y => y.WishLists).Include(x => x.Products).Where(x => x.ListId != wishLists.ListId).ToList();
            TempData["CurrentUrl"] = Request.Url.ToString();
            Wishlisturl = Convert.ToString(TempData["CurrentUrl"]);
            TempData["Wishlisturl"] = Wishlisturl;


            return View(wlistprod);
        }

        [HttpPost]
        public ActionResult ShareWishlist(FormCollection form)
        {

            string Email = form["femail"];

            SendWishlistEmail(Email);

            return View("~/Views/Home/Index.cshtml");
        }

        public void SendWishlistEmail(string Email)
        {
            string subject = "Shared Wishlist";
            string body = "Hi this user:" + " " + User.Identity.Name + " shared their wishlist with you" + " " + TempData["Wishlisturl"];

            try
            {
                new Email().SendEmail(subject, body, Email);
            }
            catch (Exception)
            {

                // throw;
            }
        }


        // GET: SavedProducts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WishListsProducts wishListsProducts = db.WishListsProducts.Find(id);
            if (wishListsProducts == null)
            {
                return HttpNotFound();
            }
            return View(wishListsProducts);
        }

        // GET: SavedProducts/Create
        public ActionResult Create(WishListsProducts wishListsProducts)
        {
            ViewBag.ProductId = new SelectList(db.Products, "ProductId", "ProductName", wishListsProducts.ProductId);
            ViewBag.ListId = new SelectList(db.WishLists, "ListId", "ListName", wishListsProducts.ListId);
            return View();
        }


        // POST: SavedProducts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]

        public ActionResult Create([Bind(Include = "ListedProductsId,ListId,TotalItems,ListUrl,ProductId")] WishListsProducts wishListsProducts, int? id, Products products)
        {
            /* var addedItem = db.WishListsProducts
                  .Single(wishListsProducts => wishListsProducts.ProductId == id);*/

            products.ProductId = Convert.ToInt32(Request.Form["BookId"]);



            if (ModelState.IsValid)
            {

                db.WishListsProducts.Add(wishListsProducts);

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else if (wishListsProducts.ListId != null)
            {

                return RedirectToAction("OurProducts", "Products");

            }


            ViewBag.ProductId = new SelectList(db.Products, "ProductId", "ProductName", wishListsProducts.ProductId);
            ViewBag.ListId = new SelectList(db.WishLists, "ListId", "ListName", wishListsProducts.ListId);
            return View(wishListsProducts);
        }



        // GET: SavedProducts/Edit/5
        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            WishListsProducts wishListsProducts = db.WishListsProducts.Find(id);

            if (wishListsProducts == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProductId = new SelectList(db.Products, "ProductId", "ProductName", wishListsProducts.ProductId);
            ViewBag.ListId = new SelectList(db.WishLists, "ListId", "ListName", wishListsProducts.ListId);
            return View(wishListsProducts);
        }

        // POST: SavedProducts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ListedProductsId,ListId,TotalItems,ListUrl,ProductId")] WishListsProducts wishListsProducts, Products products)
        {

            if (ModelState.IsValid)
            {
                db.Entry(wishListsProducts).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            ViewBag.ProductId = new SelectList(db.Products, "ProductId", "ProductName", wishListsProducts.ProductId);
            ViewBag.ListId = new SelectList(db.WishLists, "ListId", "ListName", wishListsProducts.ListId);
            return View(wishListsProducts);
        }

        // GET: SavedProducts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WishListsProducts wishListsProducts = db.WishListsProducts.Find(id);
            if (wishListsProducts == null)
            {
                return HttpNotFound();
            }
            return View(wishListsProducts);
        }

        // POST: SavedProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            WishListsProducts wishListsProducts = db.WishListsProducts.Find(id);
            db.WishListsProducts.Remove(wishListsProducts);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ShareWhishList(Int32 Id)
        {
            var req = Request.Url;
            var baseUrl = ConfigurationManager.AppSettings["SITE_URL"];
            var link = string.Format("{0}/SavedProducts/DisplayWishlist/{1}", baseUrl, Id);
            return Json(link, JsonRequestBehavior.AllowGet);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/SavedProducts/Create.cshtml
@model BookStore.Models.WishListsProducts

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>WishListsProducts</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ListId, "ListId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ListId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ListId, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.TotalItems)

        @ViewBag.ProductName

        @Html.HiddenFor(model => model.ListUrl)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, "ProductId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/SavedProducts/Delete.cshtml
@model BookStore.Models.WishListsProducts

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WishListsProducts</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Products.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Products.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WishLists.ListName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WishLists.ListName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalItems)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalItems)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ListUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ListUrl)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/SavedProducts/Details.cshtml
@model BookStore.Models.WishListsProducts

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Details</h2>

<div>
    <h4>WishListsProducts</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Products.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Products.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WishLists.ListName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WishLists.ListName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalItems)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalItems)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ListUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ListUrl)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ListedProductsId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/SavedProducts/DisplayWishlist.cshtml
@model IEnumerable<BookStore.Models.WishListsProducts>

@{
    ViewBag.Title = "DisplayWishlist";
    Layout = "~/Views/Shared/_Layout1.cshtml";

    <link href="~/Styles/StyleSheetGlow.css" rel="stylesheet" />

}
<style>
    thead, tfoot {
        display: none;
    }

    table {
        background: none !important;
        border: none !important;
    }

    tr {
        display: inline-block;
        padding: 1rem 0.5rem 1rem 0.5rem;
        margin: 1.5rem;
        border: 1px solid grey;
        border-radius: 10px;
        box-shadow: 0 0 10px;
        background-color: black;
    }

    td {
        display: block;
    }
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script type="text/javascript">

    $(function () {
        // Document.ready -> link up remove event handler
        $(".AddLink").click(function () {
            // Get the id from the link
            var recordToAdd = $(this).attr("data-id");
            if (recordToAdd != '') {
                // Perform the ajax post
                $.post("/ShoppingCart/AddToCart", { "id": recordToAdd },
                    function (data) {
                        $('#cart-status').text(data.CartCount);
                    });
            }
        });
    });</script>

<h2 class="align-content-center">Wishlist Items</h2>
<!-- Button trigger modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

    <div aria-hidden="true" class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>An item was added to your cart.</strong> To check out now simply <a href="#" class="alert-link">click here</a>.
    </div>

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                @*<h4 class="modal-title">Confirm check out.</h4>*@
            </div>
            <div class="modal-body">
                <p>Are you sure you want to checkout?</p>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Keep Shopping</button>
                <button type="submit" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "ShoppingCart")'">Check Out</button>
            </div>
        </div>
    </div>
</div>
<div id="SubmitModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title dropbtn" id="modalTitleText">Description</h4>
            </div>
            <div class="modal-body">
                <div class="container col-md-12">
                    <div id="appendDes" class="col-md-12">

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="dropbtn" data-dismiss="modal">Ok</button>
            </div>
        </div>
    </div>
</div>




@*<tr>
         <th>
            @Html.DisplayNameFor(model => model.Products.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WishLists.ListName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalItems)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ListUrl)
        </th>
        <th></th>
    </tr>*@
<body>
    @foreach (var item in Model)
    {

        <div class="card1-columns px-3">


            <div class="column1 d-flex justify-content-center p-3">
                <div class="grid1-container px-4" style="box-shadow: 0 4px 3px black; background:rgb(245, 245, 245);border-radius:4px">
                    <div class="grid1-item">

                        <div class="card1 .center">
                            <div class="card1-img .center">
                                <img src="data:image;base64,@System.Convert.ToBase64String(item.Products.ProductImage)"
                                     style="width:300px; height:300px; margin:0px; padding:10px" alt="no photo" class="adsm-image; center-url" />
                            </div>

                            <div class="card1-body">
                                <h4 class="card1-title">Name: <span class="card-value">@item.Products.ProductName</span> </h4>
                            </div>

                            <div class="card1-body">
                                <h4 class="card1-title">Price: <span class="card-value">R @item.Products.ProductPrice</span></h4>
                            </div>
                            <div class="card1-body d-flex justify-content-center">
                                <div class="d-flex p-0 pb-1">
                                    @* <span class="m-0 p-0" style="cursor: pointer" id="IncrsQty" onclick="IncrsQty()">
                                            <i class="fa fa-plus"></i>
                                        </span>*@ @if (item.Products.ProductCatergoryId != 11)
                                    {
                                        <h4 class="m-0 p-0 mx-3" id="quantity">Available Currently<span class="card-value"> @item.Products.ProductStock </span></h4>
                                    }
                                    @*<span class="m-0 p-0" id="DecrsQty" onclick="DecrsQty()">
                                            <i class="fa fa-minus" style="cursor: pointer"></i>
                                        </span>*@
                                    </div>
                                </div>


                                <div class="d-flex justify-content-center pt-2">
                                    <a style="text-align:center; align-content:center; position:center" href="#" class="AddLink AddLinkTab" data-id="@item.ProductId" data-toggle="modal" data-target="#myModal"><i class="fa fa-cart-plus" aria-hidden="true"></i> Add to cart</a>
                                    <!--@Html.ActionLink("Add to cart", "AddToCart", "ShoppingCart", new { id = item.ProductId, }, new { htmlAttributes = new { @data_toggle = "modal", @data_target = "#myModal" } })-->

                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

        }
</body>



<div>

    <button type="button" class="btn btn-outline-success" name="answer" onclick="showDiv()">Share Wishlist</button>

    <div id="sharelist" style="display:none;" class="answer_list">
        @using (Html.BeginForm("ShareWishlist", "SavedProducts"))
        {
            <label for="femail"> Enter email you wish to share this list to</label>
            <input type="email" name="femail" />
            <input type="submit" value="Share" />
            <input type="button" onclick="copyToClipboard('@Request.Url.AbsoluteUri.ToString()')" value="Share Link" />
        }

    </div>


</div>
<script>
    function showDiv() {
        document.getElementById('sharelist').style.display = "block";
    }
</script>

<script>
    function copyToClipboard(text) {
        // Create a temporary textarea element
        var textarea = document.createElement("textarea");

        // Set the value of the textarea to the text you want to copy
        textarea.value = text;

        // Append the textarea to the document
        document.body.appendChild(textarea);

        // Select the text in the textarea
        textarea.select();

        // Copy the selected text to the clipboard
        document.execCommand("copy");

        // Remove the temporary textarea from the document
        document.body.removeChild(textarea);
        alert('Link Copied!')
    }
</script>
@{ string url = TempData["CurrentUrl"].ToString(); }
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/vast-engineering/jquery-popup-overlay@2/jquery.popupoverlay.min.js"></script>

Views/SavedProducts/Edit.cshtml
@model BookStore.Models.WishListsProducts

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ListedProductsId)
        @Html.HiddenFor(model => model.ProductId)

        <div class="form-group">
            <h2> @Html.LabelFor(model => model.ListId, "ListId", htmlAttributes: new { @class = "control-label col-md-2" })</h2>
            <div class="col-md-10">
                @Html.DropDownList("ListId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ListId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Confirm" class="btn btn-default" />
            </div>
        </div>

    </div>

}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/SavedProducts/Index.cshtml
@model IEnumerable<BookStore.Models.WishListsProducts>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<style>
    .card {
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
        width: 32%;
        position: center;
        text-align: center;
        margin: auto;
        background-color: #E0E0E0;
    }

        .card:hover {
            box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
        }

    .container {
        padding: 2px 16px;
    }

    .card:hover {
        box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
    }

    .img {
        border-radius: 5px 5px 0 0;
    }

    .p:hover {
        color: red;
    }
</style>

<h2 style="ali">WishList</h2>

@foreach (var item in Model)
{ if(item.ListId == null) { 

    {
        @Html.HiddenFor(modelItem => item.ProductId)

        @Html.HiddenFor(modelItem => item.WishLists.ListName)

        @Html.HiddenFor(modelItem => item.TotalItems)

        @Html.HiddenFor(modelItem => item.ListUrl)
        <div class="card">
            <div class="container">
                <img src="data:image;base64,@System.Convert.ToBase64String(item.Products.ProductImage)"
                     style="width:400px; height:400px; margin:0px; padding:10px" alt="no photo" class="adsm-image; center-url" />

                <h4 style=" font-size: 20px;"> @Html.DisplayFor(modelItem => item.Products.ProductName)</h4>
                <p style=" font-size: 30px;">@Html.ActionLink("Save to a list", "Edit", new { id = item.ListedProductsId })</p>
            </div>
        </div>



        }
    }
}